name: Test
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and test
        run: |
          yarn

      - name: Test
        run: |
          yarn test
          npm run check
